#!/usr/bin/env bash
# Create deploy/production/.env with cryptographically random secrets for local smoke testing.
# The output file is gitignored — never commit it.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$ROOT/.env"
EXAMPLE="$ROOT/.env.example"

if [[ -f "$OUT" ]]; then
  echo "$OUT already exists; remove it to regenerate." >&2
  exit 1
fi

rand() {
  openssl rand -hex "$1"
}

PUBLIC_HOST="${FILVAULT_PUBLIC_HOST:-filvault.local}"
PUBLIC_PORT="${FILVAULT_PUBLIC_PORT:-8443}"
PUBLIC_ORIGIN="https://${PUBLIC_HOST}:${PUBLIC_PORT}"
PUBLIC_WS="wss://${PUBLIC_HOST}:${PUBLIC_PORT}"

POSTGRES_PASSWORD="$(rand 16)"
JWT_SECRET="$(rand 32)"
INVITE_CODE="invite-$(rand 8)"
S3_ACCESS="$(rand 8)"
S3_SECRET="$(rand 16)"

cat >"$OUT" <<EOF
# Generated by deploy/production/generate-env.sh — local production-like smoke only.
FILVAULT_ENV=production
FILVAULT_PUBLIC_HOST=${PUBLIC_HOST}
FILVAULT_PUBLIC_PORT=${PUBLIC_PORT}

FILVAULT_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
FILVAULT_DATABASE_URL=postgres://filvault:${POSTGRES_PASSWORD}@postgres:5432/filvault?sslmode=require

FILVAULT_METADATA_STORE=postgres
FILVAULT_OBJECT_STORE=s3
FILVAULT_S3_ENDPOINT=http://minio:9000
FILVAULT_S3_PUBLIC_ENDPOINT=${PUBLIC_ORIGIN}/filvault
FILVAULT_S3_BUCKET=filvault
FILVAULT_S3_REGION=us-east-1
FILVAULT_S3_ACCESS_KEY=${S3_ACCESS}
FILVAULT_S3_SECRET_KEY=${S3_SECRET}

FILVAULT_JWT_SECRET=${JWT_SECRET}
FILVAULT_INVITE_CODE=${INVITE_CODE}
FILVAULT_HTTP_ADDR=:8080
FILVAULT_MAILER=smtp
FILVAULT_SMTP_HOST=mailpit
FILVAULT_SMTP_PORT=1025
FILVAULT_SMTP_FROM=noreply@${PUBLIC_HOST}
FILVAULT_CORS_ALLOWED_ORIGINS=${PUBLIC_ORIGIN}
FILVAULT_TRUSTED_PROXIES=172.16.0.0/12,10.0.0.0/8,192.168.0.0/16
FILVAULT_DEFAULT_TRASH_AUTO_DELETE=false
FILVAULT_DEFAULT_TRASH_RETENTION_DAYS=30

# LiveKit disabled — enable with compose profile livekit and set keys below.
# FILVAULT_LIVEKIT_URL=http://livekit:7880
# FILVAULT_LIVEKIT_PUBLIC_URL=${PUBLIC_WS}
# FILVAULT_LIVEKIT_API_KEY=
# FILVAULT_LIVEKIT_API_SECRET=

FILVAULT_SEED_DEV_USER=false
GIN_MODE=release
EOF

echo "Wrote $OUT"
echo "Add to /etc/hosts: 127.0.0.1 ${PUBLIC_HOST}"
echo "Public origin: ${PUBLIC_ORIGIN}"
echo "Mailpit UI: http://127.0.0.1:8025"
